### PR TITLE
Add to FrameXML

### PR DESCRIPTION
**Pull request by Nightwarden24**
Adds global objects, functions and methods from the following files:

- SharedXML/Color.lua
- SharedXML/Vector2D.lua
- SharedXML/Vector3D.lua

The following functions are omitted in Vector3D.lua:

- Vector3D_ScaleBy(scalar, x, y, z)
- Vector3D_DivideBy(divisor, x, y, z)
- Vector3D_Add(leftX, leftY, leftZ, rightX, rightY, rightZ)
- Vector3D_Subtract(leftX, leftY, leftZ, rightX, rightY, rightZ)
- Vector3D_Cross(leftX, leftY, leftZ, rightX, rightY, rightZ)
- Vector3D_Dot(leftX, leftY, leftZ, rightX, rightY, rightZ)
- Vector3D_GetLengthSquared(x, y, z)
- Vector3D_GetLength(x, y, z)
- Vector3D_Normalize(x, y, z)
- Vector3D_CalculateNormalFromYawPitch(yaw, pitch)
- Vector3D_CalculateYawPitchFromNormal(x, y, z)

The following functions are omitted Vector2D.lua:

- Vector2D_ScaleBy(scalar, x, y)
- Vector2D_DivideBy(divisor, x, y)
- Vector2D_Add(leftX, leftY, rightX, rightY)
- Vector2D_Subtract(leftX, leftY, rightX, rightY)
- Vector2D_Cross(leftX, leftY, rightX, rightY)
- Vector2D_Dot(leftX, leftY, rightX, rightY)
- Vector2D_GetLengthSquared(x, y)
- Vector2D_GetLength(x, y)
- Vector2D_Normalize(x, y)
- Vector2D_CalculateAngleBetween(leftX, leftY, rightX, rightY)
- Vector2D_RotateDirection(rotationRadians, x, y)

If you need them let me know. Would you like more additions?

### CODE REVIEW

**Comment by Ketho** [comment]
`@field` currently doesn't support the `|nil` or `?` afaik, I'll have to file a ticket for sumneko.

Can you move them to `EmmyLua/Mixin`? Considering they are mixins. Otherwise it looks good to me!

**Comment by Nightwarden24** [comment]
>`@field` currently doesn't support the `|nil` or `?` afaik, ...

I understand it. Server doesn't consider such annotations. But the tooltip on hover still displays that a field may be nil. I would leave it that way for now. 

>Can you move them to `EmmyLua/Mixin`? Considering they are mixins.

Wouldn't it be better to leave them in the files in which they are defined? Then it would be easier to make changes if Blizzard changes something in them with some patch

**Comment by Ketho** [comment]
> But the tooltip on hover still displays that a field may be nil.

For me it doesn't show that a field may be nil on hover for the @field param

image

> Wouldn't it be better to leave them in the files in which they are defined? Then it would be easier to make changes if Blizzard changes something in them with some patch

I think I'll just arrange the files to be more consistent with Blizzard and put them in `EmmyLua/FrameXML/ObjectAPI`

**Comment by Nightwarden24** [comment]
Sorry, I put it wrong. I meant this

**Comment by Ketho** [comment]
Oh neat, didn't see that it still worked for completion! Still will file a ticket though

**Comment by Nightwarden24** [comment]
By the way, I forgot to say. I intentionally created a local object for a class first, and then assigned type to global object with `---@type`. Because there is such a case when using the global object at once



or



This field in both cases doesn't exist in reality. I don't know what it is: a bug or it works as it should.

**Comment by Ketho** [comment]
This seems to work as expected for me since it's an array/table of `MyClass`

image

**Comment by Nightwarden24** [comment]
Your case also had a problem, but it seems he fixed it. In the example above, if you don't specify a key, MyClass field is still suggested for some reason.

**Comment by Ketho** [comment]
> if you don't specify a key, MyClass field is still suggested for some reason.

Hmm indeed that looks like a bug, you should make a ticket for Sumneko

**Comment by Nightwarden24** [comment]
If you make an object local in class definition, the problem goes away

Yea, I should ... but too lazy. Don't want to fill in a bunch of fields

**Comment by Ketho** [comment]
Suppose I'll have to do it then, some time. I just don't want too spam summneko because I already have other more important bugs

**Comment by Nightwarden24** [comment]
Well, I won't do it anymore, since we have come to an agreement that this is probably a bug

**Pull request merged**
